version: '3.8'
services:
  web:
    image: adedoyine/demo-app:latest  # Updated image name
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=mysql://admin:${MARIADB_PASSWORD}@db/mydb
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis

  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: mydb
      MARIADB_USER: user
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
