region            = "eu-west-3"
vpc_cidr          = "10.0.0.0/16"
public_subnet_cidr = "10.0.1.0/24"
private_subnet_cidr = "10.0.2.0/24"
key_name          = "K8s-key"
instance_type     = "t3.large"
db_password = "devsecops"
mariadb_password = "safe-password"
rds_db_password  =  "safe-password"

