name: 'Terraform Infrastructure Provisioning with Security Scanning'

on:
  push:
    branches:
      - 
  pull_request:
    branches:
      - 

jobs:
  terraform:
    name: 'Terraform Plan and Apply'
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout Code'
      uses: actions/checkout@v2

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: 'Terraform Init'
      run: terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: 'Terraform Plan'
      run: terraform plan -out=tfplan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        MARIADB_PASSWORD: ${{ secrets.MARIADB_PASSWORD }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}

    - name: 'Terraform Apply'
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve "tfplan"
      env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
         DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
         MARIADB_PASSWORD: ${{ secrets.MARIADB_PASSWORD }}
         MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      
  build-and-scan:
    name: 'Build, Start Services, and Security Scan'
    runs-on: ubuntu-latest
    needs: terraform  # Ensure this job runs after Terraform plan and apply
    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
    - name: 'Checkout Code'
      uses: actions/checkout@v2

    - name: 'Set up Docker Compose'
      run: sudo apt-get update && sudo apt-get install -y docker-compose

    - name: 'Install Terraform'
      run: |
        sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get update && sudo apt-get install terraform

    - name: 'Install Snyk CLI'
      run: npm install -g snyk

    - name: 'Login to Docker Hub'
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: 'Build Docker Image'
      run: docker build -t myapp:latest .

    - name: 'Build and Start Services'
      run: docker-compose up -d --build

    - name: 'Verify Docker Daemon'
      run: docker info

    - name: 'Prepare Workspace'
      run: mkdir -p ./workspace

    - name: 'Scan Docker Image with Snyk'
      run: snyk container test myapp:latest --file=Dockerfile --severity-threshold=critical > ./workspace/snyk-scan-results.txt
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      continue-on-error: true

    - name: 'Aqua Security Scan'
      run: |
        docker run -v $(pwd)/workspace:/workspace aquasec/trivy:0.18.3 image --format json --output /workspace/trivy-scan-results.json myapp:latest
      continue-on-error: true

    - name: 'Upload Scan Results'
      uses: actions/upload-artifact@v3
      with:
        name: scan-results
        path: ./workspace/*.json
