name: 'Terraform Security Scanning'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-scan:
    name: 'Build, Start Services, and Security Scan'
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
    - name: 'Checkout Code'
      uses: actions/checkout@v2

    - name: 'Set up Docker Compose'
      run: sudo apt-get update && sudo apt-get install -y docker-compose

    - name: 'Install Terraform'
      run: |
        sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get update && sudo apt-get install terraform

    - name: 'Install Snyk CLI'
      run: npm install -g snyk

    - name: 'Build and Start Services'
      run: docker-compose up -d --build

    - name: 'Verify Docker Daemon'
      run: docker info

    - name: 'Prepare Workspace'
      run: mkdir -p ./workspace

    - name: 'Scan Docker Image with Snyk'
      run: snyk container test myapp:latest --file=Dockerfile --severity-threshold=high > ./workspace/snyk-scan-results.txt
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      continue-on-error: true

    - name: 'Aqua Security Scan'
      run: |
        docker run -v $(pwd)/workspace:/workspace aquasec/trivy:0.18.3 image --format json --output /workspace/trivy-scan-results.json myapp:latest
      continue-on-error: true

    - name: 'Upload Scan Results'
      uses: actions/upload-artifact@v3
      with:
        name: scan-results
        path: ./workspace/*.txt
