name: 'Terraform Infrastructure Provisioning with Security Scanning'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform Plan and Apply'
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
    - name: 'Checkout Code'
      uses: actions/checkout@v2

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: 'Terraform Init'
      run: terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: 'Terraform Plan'
      run: terraform plan -var="db_password=${{ secrets.DB_PASSWORD }}" -var="mariadb_password=${{ secrets.MARIADB_PASSWORD }}" -var="rds_db_password=${{ secrets.RDS_DB_PASSWORD }}" -out=tfplan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: 'Upload Terraform Plan Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: tfplan
        path: tfplan

    - name: 'Terraform Apply'
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve "tfplan"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

  snyk:
    name: 'Snyk Security Scan'
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
    - name: 'Checkout Code'
      uses: actions/checkout@v2

    - name: 'Install Snyk CLI'
      run: npm install -g snyk

    - name: 'Docker Login'
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: 'Build Docker Image'
      run: docker build -t myapp:latest .

    - name: 'Verify Docker Daemon'
      run: docker info

    - name: 'Verify Docker Image'
      run: docker images

    - name: 'Create Snyk Results Directory'
      run: mkdir -p ./workspace

    - name: 'Scan Docker Image with Snyk'
      run: snyk container test myapp:latest --file=Dockerfile --severity-threshold=high > ./workspace/snyk-scan-results.txt
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      continue-on-error: true

    - name: 'Upload Snyk Scan Results'
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: snyk-scan-results
        path: ./workspace/snyk-scan-results.txt
        if-no-files-found: warn

    - name: 'Monitor Docker Image with Snyk'
      run: snyk container monitor myapp:latest --file=Dockerfile
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      continue-on-error: true

  aqua:
    name: 'Aqua Security Scan'
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
    - name: 'Checkout Code'
      uses: actions/checkout@v2

    - name: 'Docker Login'
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: 'Build Docker Image'
      run: docker build -t myapp:latest .

    - name: 'Verify Docker Daemon'
      run: docker info

    - name: 'Verify Docker Image'
      run: docker images

    - name: 'Create Aqua Results Directory'
      run: mkdir -p ./workspace

    - name: 'Aqua Security Scan'
      run: |
        docker run -v $(pwd)/workspace:/workspace aquasec/trivy:latest image --format json --output /workspace/results.json myapp:latest
      continue-on-error: true

    - name: 'Upload Aqua Security Scan Results'
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: aqua-scan-results
        path: ./workspace/results.json
        if-no-files-found: warn
